create table if not exists public.attendance_schedules (
  id text primary key,
  label text not null unique,
  start_time text not null,
  end_time text not null,
  check (start_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  check (end_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  check (end_time > start_time)
);

insert into public.attendance_schedules (id, label, start_time, end_time)
values
  ('employee-morning', 'Karyawan Shift Pagi', '07:00', '17:00'),
  ('employee-afternoon', 'Karyawan Shift Siang', '14:00', '22:00'),
  ('admin-1', 'Admin 1', '07:00', '17:00'),
  ('admin-2', 'Admin 2', '09:00', '18:00'),
  ('coordinator', 'Koordinator', '11:00', '19:30')
on conflict (id) do nothing;

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  created_local_date date not null default current_date
);

create unique index if not exists people_name_case_insensitive
  on public.people (lower(name));

create table if not exists public.custom_fields (
  id bigint generated by default as identity primary key,
  label text not null,
  type text not null check (type in ('text', 'number', 'date', 'select', 'checkbox')),
  options_json jsonb not null default '[]'::jsonb,
  required boolean not null default false
);

create unique index if not exists custom_fields_label_case_insensitive
  on public.custom_fields (lower(label));

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  person_name text not null,
  attendance_type text not null check (attendance_type in ('datang', 'pulang')),
  note text not null default '',
  values_json jsonb not null default '{}'::jsonb,
  photo_path text not null,
  photo_content_type text not null check (photo_content_type in ('image/jpeg', 'image/png', 'image/webp')),
  created_at timestamptz not null default now(),
  created_local_date date not null,
  schedule_id text not null default 'employee-morning'
    references public.attendance_schedules(id),
  schedule_start_time text not null,
  schedule_end_time text not null
);

create unique index if not exists attendance_person_date_type_case_insensitive
  on public.attendance (lower(person_name), created_local_date, attendance_type);

create index if not exists attendance_created_local_date_idx
  on public.attendance (created_local_date);

create or replace function public.enforce_daily_attendance_schedule()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  existing_schedule_id text;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(lower(new.person_name) || ':' || new.created_local_date::text, 0)
  );

  select attendance.schedule_id into existing_schedule_id
  from public.attendance
  where lower(attendance.person_name) = lower(new.person_name)
    and attendance.created_local_date = new.created_local_date
  order by attendance.created_at
  limit 1;

  if found and existing_schedule_id <> new.schedule_id then
    raise exception 'Attendance shift must match the first shift selected for this date.'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists attendance_schedule_consistency on public.attendance;
create trigger attendance_schedule_consistency
before insert or update
on public.attendance
for each row execute function public.enforce_daily_attendance_schedule();

create table if not exists public.admins (
  id smallint primary key check (id = 1),
  username text not null,
  salt text not null,
  password_hash text not null,
  password_scheme text not null default 'scrypt' check (password_scheme in ('scrypt', 'pbkdf2'))
);

create unique index if not exists admins_username_case_insensitive
  on public.admins (lower(username));

create table if not exists public.attendance_rules (
  id smallint primary key check (id = 1),
  start_time text not null default '08:00',
  end_time text not null default '17:00',
  tolerance_minutes integer not null default 5 check (tolerance_minutes between 0 and 180),
  late_limit_minutes integer not null default 15 check (late_limit_minutes between 1 and 360)
);

insert into public.attendance_rules (id, start_time, end_time, tolerance_minutes, late_limit_minutes)
values (1, '08:00', '17:00', 5, 15)
on conflict (id) do nothing;

create table if not exists public.admin_auth_attempts (
  attempt_key text primary key,
  window_started_at timestamptz not null,
  attempt_count integer not null
);

create or replace function public.register_admin_auth_attempt(p_attempt_key text)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_count integer;
begin
  insert into public.admin_auth_attempts (attempt_key, window_started_at, attempt_count)
  values (p_attempt_key, now(), 1)
  on conflict (attempt_key) do update
  set window_started_at = case
        when public.admin_auth_attempts.window_started_at <= now() - interval '1 minute' then now()
        else public.admin_auth_attempts.window_started_at
      end,
      attempt_count = case
        when public.admin_auth_attempts.window_started_at <= now() - interval '1 minute' then 1
        else public.admin_auth_attempts.attempt_count + 1
      end
  returning attempt_count into current_count;
  return current_count;
end;
$$;

revoke all on function public.register_admin_auth_attempt(text) from public, anon, authenticated;
grant execute on function public.register_admin_auth_attempt(text) to service_role;

alter table public.people enable row level security;
alter table public.custom_fields enable row level security;
alter table public.attendance enable row level security;
alter table public.attendance_schedules enable row level security;
alter table public.admins enable row level security;
alter table public.attendance_rules enable row level security;
alter table public.admin_auth_attempts enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'attendance-photos',
  'attendance-photos',
  false,
  3670016,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
